server:
  port: 8080
spring:
  application:
    name: Api Gateway
  cloud:
    gateway:
      routes:
        - id: Customer
          uri: lb://Customer/
          predicates:
          - Path=/customer/**
        - id: Account
          uri: lb://Account/
          predicates:
          - Path=/account/**